### ISSUE TITLE
when will you release train code？

### ISSUE THREAD

**Issue by Johnson-yue** [williamyang1991/TET-GAN#1]
Hi，It is so interesting project，I want to learn it， if you release train code，please tell me，thank you very much

**Comment by williamyang1991** [comment]
Sure, I will notify you when our training code is ready.

**Comment by williamyang1991** [comment]
> Hi，It is so interesting project，I want to learn it， if you release train code，please tell me，thank you very much

Hi, the training code is released. Hope it is useful to you.

**Comment by Johnson-yue** [comment]
Thank you very much!!! I will try this ,and I have see your new paper <<Text Style Transfer via Shape-Matching GAN>>!!!  great job!
